from folio_pdf.core import lib
from folio_pdf.object import AbstractFolioObject
import ctypes as ct


class Div(AbstractFolioObject):
    _requires_close = True

    def __init__(self):
        self._div_handle = -1

    @property
    def handle(self) -> ct.c_uint64:
        return ct.c_uint64(self._div_handle)

    def close(self):
        lib.folio_div_free(self.handle)

    def add(self): ...

    def set_padding(self): ...

    def set_background(self): ...

    def set_border(self): ...

    def set_width(self): ...

    def set_min_height(self): ...

    def set_max_width(self): ...

    def set_min_width(self): ...

    def set_width_percent(self): ...

    def set_aspect_ratio(self): ...

    def set_kepp_together(self): ...

    def set_border_radius_per_corner(self): ...

    def set_hcenter(self): ...

    def set_hright(self): ...

    def set_clear(self): ...

    def set_outline(self): ...

    def add_box_shadow(self): ...

    def set_space_before(self): ...

    def set_spage_after(self): ...

    def set_border_radius(self): ...

    def set_opacity(self): ...

    def set_overflow(self): ...

    def set_tag(self): ...

    def set_box_shadow(self): ...

    def set_max_height(self): ...
