"""
Copyright 2026 Gbenga Adeyi and Folio PDF Authors
SPDX-License-Identifier: Apache-2.0
"""


class FolioPDFException(Exception): ...


class DocumentException(FolioPDFException): ...


class PageException(FolioPDFException): ...


class ParagraphException(FolioPDFException): ...


class HeadingException(FolioPDFException): ...


class TableException(FolioPDFException): ...


class TableCellException(FolioPDFException): ...


class WriteOptionsException(FolioPDFException): ...


class ImageException(FolioPDFException): ...


class ImageElementException(FolioPDFException): ...


class DivException(FolioPDFException): ...


class ListException(FolioPDFException): ...


class LinkException(FolioPDFException): ...
