class FolioPDFException(Exception): ...


class DocumentException(FolioPDFException): ...


class PageException(FolioPDFException): ...


class ParagraphException(FolioPDFException): ...


class HeadingException(FolioPDFException): ...
