"""
Copyright 2026 Gbenga Adeyi and Folio PDF Authors
SPDX-License-Identifier: Apache-2.0
"""

from folio_pdf.core import lib
from folio_pdf.object import AbstractFolioObject
import ctypes as ct


class Flex(AbstractFolioObject):
    _requires_close = True

    def __init__(self):
        self._flex_handle = -1

    @property
    def handle(self) -> ct.c_uint64:
        return ct.c_uint64(self._flex_handle)

    def close(self):
        lib.folio_flex_free(self.handle)

    def add(self): ...

    def add_item(self): ...

    def set_direction(self): ...

    def set_justify_content(self): ...

    def set_align_items(self): ...

    def set_wrap(self): ...

    def set_gap(self): ...

    def set_padding(self): ...

    def set_background(self): ...

    def set_space_before(self): ...

    def set_space_after(self): ...

    def set_row_gap(self): ...

    def set_column_gap(self): ...

    def set_align_content(self): ...

    def set_borders(self): ...

    def set_padding_all(self): ...

    def set_border(self): ...
