from folio_pdf.core import lib


class Page:
    def __init__(self):
        self._page_handle = -1

    @classmethod
    def _new_from_handle(cls, page_handle: int):
        obj = cls.__new__(cls)
        cls._page_handle = page_handle
        return obj

    def add_text(self): ...

    def add_text_embedded(self): ...

    def add_image(self): ...

    def add_link(self): ...

    def add_internal_link(self): ...

    def add_text_annotation(self): ...

    def set_opacity(self): ...

    def set_rotate(self): ...

    def set_crop_box(self): ...

    def set_trim_box(self): ...

    def set_bleed_box(self): ...

    def set_art_box(self): ...

    def set_size(self): ...

    def add_page_link(self): ...

    def set_opacity_fill_stroke(self): ...

    def add_highlight(self): ...

    def add_underline_annotation(self): ...

    def add_squiggly(self): ...

    def add_strikeout(self): ...
