from folio_pdf.font import Font


class Paragraph:
    def __init__(self, text: str, font: Font, font_size: float): ...

    @classmethod
    def new_embedded(cls, text: str, font: Font, font_size: float): ...

    def close(self): ...

    def set_align(self): ...

    def set_leading(self): ...

    def set_space_before(self): ...

    def set_space_after(self): ...

    def set_background(self): ...

    def set_first_indent(self): ...

    def set_orphans(self): ...

    def set_widows(self): ...

    def set_ellipsis(self): ...

    def set_word_break(self): ...

    def set_hyphens(self): ...

    def set_text_align_last(self): ...

    def add_run(self): ...
