from folio_pdf.element import AbstractPDFElement


class Table(AbstractPDFElement):
    def __init__(self):
        self._table_ptr = ...

    def set_column_widths(self): ...

    def set_border_collapse(self): ...

    def set_cell_spacing(self): ...

    def set_auto_column_widths(self): ...

    def set_min_width(self): ...

    def add_row(self): ...

    def add_header_row(self): ...

    def add_footer_row(self): ...
